# Generated by Django 3.0.4 on 2020-03-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_id',
            field=models.IntegerField(default=1),
        ),
    ]
