# Generated by Django 3.0.4 on 2020-03-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_theme_theme_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['theme_id']},
        ),
    ]
