# Generated by Django 3.0.4 on 2020-03-10 02:45

from django.db import migrations, models
import intro.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20200309_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=intro.models.get_image_path),
        ),
    ]
